include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Unbound-WRT (DPI bypass)
LUCI_DEPENDS:=+nfqws-unbound
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-unbound
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

PKG_LICENSE:=GPL-3.0-only
PKG_MAINTAINER:=Unbound-WRT Project

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
