package engine

import "path/filepath"

// GetAdvancedProfiles returns top 10 verified working profiles
func GetAdvancedProfiles(luaDir string) []Profile {
	listsDir, _ := GetListsDir()
	windivertDir, _ := GetWinDivertFilterDir()
	
	return []Profile{
		{
			Name: "Advanced 1 (hostfakesplit + MD5)",
			Args: []string{
				"--wf-tcp-out=80,443,2053,2083,2087,2096,8443",
				"--wf-udp-out=443,19294-19344,50000-50100",
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.discord_media.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.stun.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.wireguard.txt")),
				"--filter-udp=443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=quic_initial",
				"--lua-desync=fake:blob=quic_google:repeats=6",
				"--new",
				"--filter-l7=discord,stun",
				"--payload=stun,discord_ip_discovery",
				"--lua-desync=fake:blob=fake_default_udp:repeats=6",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist-domains=discord.media",
				"--lua-desync=hostfakesplit:host=ozon.ru:tcp_ts=-1000:tcp_md5:repeats=4",
				"--new",
				"--filter-tcp=80,443",
				"--hostlist-domains=googlevideo.com",
				"--out-range=-d8",
				"--lua-desync=hostfakesplit:host=ozon.ru:tcp_ts=-1000:tcp_md5:repeats=4",
				"--new",
				"--filter-tcp=80,443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "youtube.txt")),
				"--out-range=-d8",
				"--lua-desync=hostfakesplit:host=ozon.ru:tcp_ts=-1000:tcp_md5:repeats=4",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "discord.txt")),
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "other.txt")),
				"--out-range=-d8",
				"--lua-desync=hostfakesplit:host=ozon.ru:tcp_ts=-1000:tcp_md5:repeats=4",
				"--new",
				"--filter-tcp=80,443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--lua-desync=hostfakesplit:host=ozon.ru:repeats=4:tcp_ts=-600000:tcp_md5",
				"--new",
				"--filter-udp=443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=quic_initial",
				"--lua-desync=fake:blob=quic_google:repeats=6",
				"--new",
				"--filter-tcp=80,443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--lua-desync=hostfakesplit:host=ozon.ru:repeats=4:tcp_ts=-600000",
			},
		},
		{
			Name: "Advanced 2 (fake blob + seq)",
			Args: []string{
				"--wf-tcp-out=80,443,2053,2083,2087,2096,8443",
				"--wf-udp-out=443,19294-19344,50000-50100",
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.discord_media.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.stun.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.wireguard.txt")),
				"--filter-udp=443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=quic_initial",
				"--lua-desync=fake:blob=quic_google:repeats=6",
				"--new",
				"--filter-l7=discord,stun",
				"--payload=stun,discord_ip_discovery",
				"--lua-desync=fake:blob=fake_default_udp:repeats=6",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist-domains=discord.media",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "youtube.txt")),
				"--out-range=-d8",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "discord.txt")),
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "other.txt")),
				"--out-range=-d10",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=tls_client_hello",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-udp=443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=quic_initial",
				"--lua-desync=fake:blob=quic_google:repeats=6",
				"--new",
				"--filter-tcp=80,443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=tls_client_hello",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
			},
		},
		{
			Name: "Advanced 3 (fakedsplit)",
			Args: []string{
				"--wf-tcp-out=80,443,2053,2083,2087,2096,8443",
				"--wf-udp-out=443,19294-19344,50000-50100",
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.discord_media.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.stun.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.wireguard.txt")),
				"--filter-udp=443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--lua-desync=fake:blob=quic_google:repeats=11",
				"--new",
				"--filter-l7=discord,stun",
				"--payload=stun,discord_ip_discovery",
				"--lua-desync=fake:blob=fake_default_udp:repeats=6",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist-domains=discord.media",
				"--lua-desync=fake:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com:repeats=8:tcp_seq=2",
				"--lua-desync=fakedsplit:pos=2:repeats=8:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443",
				"--hostlist-domains=googlevideo.com",
				"--out-range=-d8",
				"--lua-desync=fake:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com:repeats=8:tcp_seq=2",
				"--lua-desync=fakedsplit:pos=2:repeats=8:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "youtube.txt")),
				"--out-range=-d8",
				"--lua-desync=fake:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com:repeats=8:tcp_seq=2",
				"--lua-desync=fakedsplit:pos=2:repeats=8:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "discord.txt")),
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "other.txt")),
				"--out-range=-d10",
				"--lua-desync=fake:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com:repeats=8:tcp_seq=2",
				"--lua-desync=fakedsplit:pos=2:repeats=8:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--lua-desync=fake:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com:repeats=8:tcp_seq=2",
				"--lua-desync=fakedsplit:pos=2:repeats=8:tcp_seq=2",
				"--new",
				"--filter-udp=443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--lua-desync=fake:blob=quic_google:repeats=11",
				"--new",
				"--filter-tcp=80,443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--lua-desync=fake:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com:repeats=8:tcp_seq=2",
				"--lua-desync=fakedsplit:pos=2:repeats=8:tcp_seq=2",
			},
		},
		{
			Name: "Advanced 4 (fake TLS variant)",
			Args: []string{
				"--wf-tcp-out=80,443,2053,2083,2087,2096,8443",
				"--wf-udp-out=443,19294-19344,50000-50100",
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.discord_media.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.stun.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.wireguard.txt")),
				"--filter-udp=443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=quic_initial",
				"--lua-desync=fake:blob=quic_google:repeats=6",
				"--new",
				"--filter-l7=discord,stun",
				"--payload=stun,discord_ip_discovery",
				"--lua-desync=fake:blob=fake_default_udp:repeats=6",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist-domains=discord.media",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "youtube.txt")),
				"--out-range=-d8",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "discord.txt")),
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "other.txt")),
				"--out-range=-d10",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=tls_client_hello",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-udp=443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=quic_initial",
				"--lua-desync=fake:blob=quic_google:repeats=6",
				"--new",
				"--filter-tcp=80,443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=tls_client_hello",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
			},
		},
		{
			Name: "Advanced 5 (alternative fake)",
			Args: []string{
				"--wf-tcp-out=80,443,2053,2083,2087,2096,8443",
				"--wf-udp-out=443,19294-19344,50000-50100",
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.discord_media.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.stun.txt")),
				"--wf-raw-part=@" + filepath.ToSlash(filepath.Join(windivertDir, "windivert_part.wireguard.txt")),
				"--filter-udp=443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=quic_initial",
				"--lua-desync=fake:blob=quic_google:repeats=6",
				"--new",
				"--filter-l7=discord,stun",
				"--payload=stun,discord_ip_discovery",
				"--lua-desync=fake:blob=fake_default_udp:repeats=6",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist-domains=discord.media",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "youtube.txt")),
				"--out-range=-d8",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443,1080,2053,2083,2087,2096,8443",
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "discord.txt")),
				"--hostlist=" + filepath.ToSlash(filepath.Join(listsDir, "other.txt")),
				"--out-range=-d10",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-tcp=80,443",
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=tls_client_hello",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
				"--new",
				"--filter-udp=443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=quic_initial",
				"--lua-desync=fake:blob=quic_google:repeats=6",
				"--new",
				"--filter-tcp=80,443",
				"--ipset=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-all.txt")),
				"--ipset-exclude=" + filepath.ToSlash(filepath.Join(listsDir, "ipset-exclude.txt")),
				"--payload=tls_client_hello",
				"--lua-desync=fake:blob=tls_google:repeats=6:tcp_seq=2",
			},
		},
	}
}
