//go:build darwin

package historyid

import (
	"reflect"
	"testing"
)

const sampleResolvConf = `# generated by locationd
search example.test
nameserver 192.168.2.1
nameserver fe80::1%en0
options edns0

not a directive
`

func TestParseResolvConfTextReadsNameservers(t *testing.T) {
	got := parseResolvConfText([]byte(sampleResolvConf))
	want := []string{"192.168.2.1", "fe80::1"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("parseResolvConfText() = %v, want %v", got, want)
	}
}

func TestParseResolvConfTextOrderIndependentAndDeduplicated(t *testing.T) {
	a := parseResolvConfText([]byte("nameserver 1.1.1.1\nnameserver 8.8.8.8\nnameserver 1.1.1.1\n"))
	b := parseResolvConfText([]byte("nameserver 1.1.1.1\nnameserver 1.1.1.1\nnameserver 8.8.8.8\n"))
	want := []string{"1.1.1.1", "8.8.8.8"}
	if !reflect.DeepEqual(a, want) || !reflect.DeepEqual(b, want) {
		t.Fatalf("got %v and %v, want %v", a, b, want)
	}
}

func TestParseResolvConfTextGarbageYieldsNothing(t *testing.T) {
	cases := map[string]string{
		"empty":      "",
		"binary":     "\x00\xfe\xff",
		"no value":   "nameserver\nnameserver   \n",
		"other keys": "domain a.test\nsearch b.test\noptions ndots:2\n",
	}
	for name, doc := range cases {
		if got := parseResolvConfText([]byte(doc)); got != nil {
			t.Errorf("parseResolvConfText(%s) = %v, want nil", name, got)
		}
	}
}

func TestDarwinFactsAreExplicitlyAbsentWhereUnavailable(t *testing.T) {
	// Documented choices: no unprivileged gateway source, no profile identity.
	if got := readGateways(nil); got != nil {
		t.Fatalf("readGateways() = %v, want nil", got)
	}
	if got := readNetworkProfile(); got != "" {
		t.Fatalf("readNetworkProfile() = %q, want \"\"", got)
	}
}
