//go:build linux

package historyid

import (
	"net"
	"reflect"
	"testing"
)

const sampleRoute = `Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT
eth0	00000000	0102A8C0	0003	0	0	0	00000000	0	0	0
eth0	00F0A8C0	00000000	0001	0	0	0	00F0FFFF	0	0	0
eth1	00000000	00000000	0001	0	0	0	00000000	0	0	0
wlan0	00000000	FE01A8C0	0003	0	0	0	00000000	0	0	0
`

func TestParseProcNetRouteFindsDefaultRouteGateways(t *testing.T) {
	got := parseProcNetRoute([]byte(sampleRoute))
	want := []string{"192.168.1.254", "192.168.2.1"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("parseProcNetRoute() = %v, want %v", got, want)
	}
}

func TestParseProcNetRouteHexIsLittleEndian(t *testing.T) {
	cases := map[string]string{
		"0102A8C0": "192.168.2.1",
		"FE01A8C0": "192.168.1.254",
		"01010101": "1.1.1.1",
		"0000000A": "10.0.0.0",
		"FFFFFFFF": "255.255.255.255",
	}
	for field, want := range cases {
		got, ok := parseRouteHexIPv4(field)
		if !ok {
			t.Fatalf("parseRouteHexIPv4(%q) reported failure", field)
		}
		if got != want {
			t.Errorf("parseRouteHexIPv4(%q) = %q, want %q", field, got, want)
		}
	}
}

func TestParseProcNetRouteIgnoresNonDefaultDestinations(t *testing.T) {
	// Only a route with a zero destination is a default route; the specific
	// subnet rows must contribute nothing.
	dump := "Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT\n" +
		"eth0 00F0A8C0 0102A8C0 0001 0 0 0 00F0FFFF 0 0 0\n" +
		"eth0 0000F0A8 C0A80201 0001 0 0 0 00F0FFFF 0 0 0\n"
	if got := parseProcNetRoute([]byte(dump)); got != nil {
		t.Fatalf("parseProcNetRoute() on non-default routes = %v, want nil", got)
	}
}

func TestParseProcNetRouteTreatsZeroGatewayAsOnLink(t *testing.T) {
	// A default route with a zero gateway is on-link: there is no next hop, and
	// "0.0.0.0" must never be reported as a gateway.
	dump := "Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT\n" +
		"eth0 00000000 00000000 0001 0 0 0 00000000 0 0 0\n"
	got := parseProcNetRoute([]byte(dump))
	if got != nil {
		t.Fatalf("parseProcNetRoute() = %v, want nil for on-link default route", got)
	}
}

func TestParseProcNetRoutePairsCarriesInterfaceName(t *testing.T) {
	pairs := parseProcNetRoutePairs([]byte(sampleRoute))
	want := []routeGateway{
		{iface: "eth0", gateway: "192.168.2.1"},
		{iface: "wlan0", gateway: "192.168.1.254"},
	}
	if !reflect.DeepEqual(pairs, want) {
		t.Fatalf("parseProcNetRoutePairs() = %v, want %v", pairs, want)
	}
}

func TestParseProcNetRouteGarbageYieldsNothing(t *testing.T) {
	cases := map[string]string{
		"empty":        "",
		"binary":       "\x00\xff\xfe\xfd",
		"blank lines":  "\n\n\n",
		"short row":    "eth0 00000000\n",
		"non hex":      "eth0 00000000 zzzzZZZZ 0003 0 0 0 00000000 0 0 0\n",
		"short hex":    "eth0 00000000 0102 0003 0 0 0 00000000 0 0 0\n",
		"hex overflow": "eth0 00000000 0102A8C0FFFF 0003 0 0 0 00000000 0 0 0\n",
		"dest not hex": "eth0 ZZZZZZZZ 0102A8C0 0003 0 0 0 00000000 0 0 0\n",
		"huge value":   "eth0 00000000 FFFFFFFFFFFFFFFF 0003 0 0 0 00000000 0 0 0\n",
	}
	for name, dump := range cases {
		if got := parseProcNetRoute([]byte(dump)); got != nil {
			t.Errorf("parseProcNetRoute(%s) = %v, want nil", name, got)
		}
	}
}

const sampleResolvConf = `# generated by resolvconf(8)
search example.test
nameserver 127.0.0.53
nameserver 192.168.2.1#commented tail

options edns0 trust-ad

nameserver    FE80::1%eth0
nameserver not-an-ip-here
`

func TestParseResolvConfReadsNameserversIgnoringCommentsAndBlanks(t *testing.T) {
	got := parseResolvConf([]byte(sampleResolvConf))
	want := []string{"127.0.0.53", "192.168.2.1", "fe80::1", "not-an-ip-here"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("parseResolvConf() = %v, want %v", got, want)
	}
}

func TestParseResolvConfStripsZoneAndNormalizes(t *testing.T) {
	got := parseResolvConf([]byte("nameserver FE80::0001%eth0\n"))
	want := []string{"fe80::1"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("parseResolvConf() = %v, want %v", got, want)
	}
}

func TestParseResolvConfIgnoresOtherDirectives(t *testing.T) {
	doc := "domain example.test\noptions ndots:2\nsearch a.test b.test\nnameserver\nnameserver   \n"
	if got := parseResolvConf([]byte(doc)); got != nil {
		t.Fatalf("parseResolvConf() = %v, want nil", got)
	}
}

func TestParseResolvConfGarbageYieldsNothing(t *testing.T) {
	cases := map[string]string{
		"empty":     "",
		"binary":    "\x00\xfe\xff",
		"crlf only": "\r\n\r\n",
	}
	for name, doc := range cases {
		if got := parseResolvConf([]byte(doc)); got != nil {
			t.Errorf("parseResolvConf(%s) = %v, want nil", name, got)
		}
	}
}

// Order independence: the kernel's and the resolver's row order is not
// semantic, so a reordered document must produce an identical result.
func TestParsersAreOrderIndependent(t *testing.T) {
	routeA := "Iface Destination Gateway Flags RefCnt Use\neth0 00000000 0102A8C0 0003 0 0\nwlan0 00000000 FE01A8C0 0003 0 0\n"
	routeB := "Iface Destination Gateway Flags RefCnt Use\nwlan0 00000000 FE01A8C0 0003 0 0\neth0 00000000 0102A8C0 0003 0 0\n"
	if a, b := parseProcNetRoute([]byte(routeA)), parseProcNetRoute([]byte(routeB)); !reflect.DeepEqual(a, b) {
		t.Fatalf("parseProcNetRoute order dependent: %v vs %v", a, b)
	}

	resolvA := "nameserver 127.0.0.53\nnameserver 192.168.2.1\n"
	resolvB := "nameserver 192.168.2.1\nnameserver 127.0.0.53\n"
	if a, b := parseResolvConf([]byte(resolvA)), parseResolvConf([]byte(resolvB)); !reflect.DeepEqual(a, b) {
		t.Fatalf("parseResolvConf order dependent: %v vs %v", a, b)
	}
}

// Duplicate rows collapse: a second identical default route on the same or a
// different interface is the same fact.
func TestParsersDeduplicate(t *testing.T) {
	dump := "Iface Destination Gateway Flags RefCnt Use\neth0 00000000 0102A8C0 0003 0 0\neth1 00000000 0102A8C0 0003 0 0\n"
	got := parseProcNetRoute([]byte(dump))
	want := []string{"192.168.2.1"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("parseProcNetRoute() = %v, want %v", got, want)
	}
	if got := parseResolvConf([]byte("nameserver 1.1.1.1\nnameserver 1.1.1.1\n")); !reflect.DeepEqual(got, []string{"1.1.1.1"}) {
		t.Fatalf("parseResolvConf() = %v, want [1.1.1.1]", got)
	}
}

// The real readers must not panic on whatever this host's procfs looks like,
// and must never fabricate an unusable value. A nil result is legitimate: an
// absent gateway or resolver set only makes history reuse more conservative.
func TestReadersNeverFabricateUnusableValues(t *testing.T) {
	ifaces, err := net.Interfaces()
	if err != nil {
		t.Skipf("interfaces unavailable: %v", err)
	}
	for _, g := range readGateways(ifaces) {
		if g == "" || g == "0.0.0.0" {
			t.Fatalf("readGateways() returned unusable gateway %q", g)
		}
	}
	for _, r := range readResolvers() {
		if r == "" {
			t.Fatal("readResolvers() returned an empty resolver entry")
		}
	}
}

func TestReadNetworkProfileIsExplicitlyAbsent(t *testing.T) {
	// Documented choice: Linux has no shell-free stable profile identity, so
	// the profile is absent rather than invented.
	if got := readNetworkProfile(); got != "" {
		t.Fatalf("readNetworkProfile() = %q, want \"\"", got)
	}
}
