// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function AddSubscription(arg1:string):Promise<Array<engine.XrayNode>>;

export function AutoSelectProfile(arg1:string):Promise<string>;

export function AutoTune():Promise<string>;

export function CheckForUpdates(arg1:string):Promise<engine.UpdateInfo>;

export function GenerateXrayConfig(arg1:string):Promise<void>;

export function GetCurrentPing():Promise<{[key: string]: any}>;

export function GetEngineNames():Promise<Array<string>>;

export function GetLivePing():Promise<{[key: string]: any}>;

export function GetLogs():Promise<Array<string>>;

export function GetProfiles(arg1:string):Promise<Array<string>>;

export function GetSettings():Promise<engine.Settings>;

export function GetStatus():Promise<string>;

export function GetSystemInfo():Promise<{[key: string]: string}>;

export function GetXrayNodes():Promise<Array<engine.XrayNode>>;

export function HideToTray():Promise<void>;

export function LoadCustomScript():Promise<string>;

export function SaveCustomScript(arg1:string):Promise<void>;

export function SaveSettings(arg1:engine.Settings):Promise<void>;

export function ShowFromTray():Promise<void>;

export function StartEngine(arg1:string,arg2:string):Promise<void>;

export function StopEngine():Promise<void>;

export function TestProfile(arg1:string,arg2:string):Promise<string>;

export function UpdateLists():Promise<void>;
