// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSelectProfile(arg1:string):Promise<string>;

export function AutoTune():Promise<string>;

export function GetCurrentPing():Promise<{[key: string]: any}>;

export function GetEngineNames():Promise<Array<string>>;

export function GetLogs():Promise<Array<string>>;

export function GetProfiles(arg1:string):Promise<Array<string>>;

export function GetStatus():Promise<string>;

export function GetSystemInfo():Promise<{[key: string]: string}>;

export function HideToTray():Promise<void>;

export function LoadCustomScript():Promise<string>;

export function SaveCustomScript(arg1:string):Promise<void>;

export function ShowFromTray():Promise<void>;

export function StartEngine(arg1:string,arg2:string):Promise<void>;

export function StopEngine():Promise<void>;

export function TestProfile(arg1:string,arg2:string):Promise<string>;
