// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function AutoSelectProfile(arg1:string):Promise<string>;

export function AutoTune():Promise<string>;

export function CancelAutoTune():Promise<void>;

export function CheckForUpdates(arg1:string):Promise<engine.UpdateInfo>;

export function CleanOldTests(arg1:number):Promise<void>;

export function ClearDiscordCache():Promise<void>;

export function DisableAutoStart():Promise<void>;

export function EnableAutoStart():Promise<void>;

export function GenerateCustomBlob(arg1:string,arg2:string):Promise<string>;

export function GetAutoStartInfo():Promise<Record<string, string>>;

export function GetBlobList():Promise<Array<engine.BlobPayload>>;

export function GetCurrentPing():Promise<Record<string, any>>;

export function GetEngineNames():Promise<Array<string>>;

export function GetLivePing():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function GetProfileCategories():Promise<Array<string>>;

export function GetProfiles(arg1:string):Promise<Array<string>>;

export function GetProfilesByCategory(arg1:string):Promise<Array<engine.AdvancedProfile>>;

export function GetSettings():Promise<engine.Settings>;

export function GetStatus():Promise<string>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function GetTestAnalytics():Promise<engine.TestAnalytics>;

export function GetTestHistory():Promise<Array<engine.TestSession>>;

export function HideToTray():Promise<void>;

export function IsAutoStartEnabled():Promise<boolean>;

export function LoadCustomScript():Promise<string>;

export function RunAdvancedTests(arg1:string,arg2:number):Promise<string>;

export function RunDiagnostics():Promise<engine.DiagnosticsReport>;

export function SaveCustomScript(arg1:string):Promise<void>;

export function SaveSettings(arg1:engine.Settings):Promise<void>;

export function ShowFromTray():Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function StartEngine(arg1:string,arg2:string):Promise<void>;

export function StopEngine():Promise<void>;

export function TestProfile(arg1:string,arg2:string):Promise<string>;

export function UpdateLists():Promise<void>;
