// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDefenderExclusion() {
  return window['go']['main']['App']['AddDefenderExclusion']();
}

export function AutoReconnectMonitor() {
  return window['go']['main']['App']['AutoReconnectMonitor']();
}

export function AutoTune() {
  return window['go']['main']['App']['AutoTune']();
}

export function CancelAutoTune() {
  return window['go']['main']['App']['CancelAutoTune']();
}

export function CancelDoctor(arg1) {
  return window['go']['main']['App']['CancelDoctor'](arg1);
}

export function CheckAllUpdates() {
  return window['go']['main']['App']['CheckAllUpdates']();
}

export function CheckConflicts() {
  return window['go']['main']['App']['CheckConflicts']();
}

export function CheckDiscordRunning() {
  return window['go']['main']['App']['CheckDiscordRunning']();
}

export function CheckPrivileges() {
  return window['go']['main']['App']['CheckPrivileges']();
}

export function ClearDiscordCache(arg1) {
  return window['go']['main']['App']['ClearDiscordCache'](arg1);
}

export function DisableAutoStart() {
  return window['go']['main']['App']['DisableAutoStart']();
}

export function EnableAutoStart() {
  return window['go']['main']['App']['EnableAutoStart']();
}

export function EnableTCPTimestamps() {
  return window['go']['main']['App']['EnableTCPTimestamps']();
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function GenerateDiagnosticReport() {
  return window['go']['main']['App']['GenerateDiagnosticReport']();
}

export function GenerateDoctorReport(arg1) {
  return window['go']['main']['App']['GenerateDoctorReport'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoStartTaskInfo() {
  return window['go']['main']['App']['GetAutoStartTaskInfo']();
}

export function GetBypassLists() {
  return window['go']['main']['App']['GetBypassLists']();
}

export function GetDoctorRunState(arg1) {
  return window['go']['main']['App']['GetDoctorRunState'](arg1);
}

export function GetEngineNames() {
  return window['go']['main']['App']['GetEngineNames']();
}

export function GetFavoriteProfiles() {
  return window['go']['main']['App']['GetFavoriteProfiles']();
}

export function GetLivePing() {
  return window['go']['main']['App']['GetLivePing']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetOSPlatform() {
  return window['go']['main']['App']['GetOSPlatform']();
}

export function GetProfiles(arg1) {
  return window['go']['main']['App']['GetProfiles'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetStatusInfo() {
  return window['go']['main']['App']['GetStatusInfo']();
}

export function GetStructuredLogs() {
  return window['go']['main']['App']['GetStructuredLogs']();
}

export function GetSystemComponentState() {
  return window['go']['main']['App']['GetSystemComponentState']();
}

export function HideWindowToTray() {
  return window['go']['main']['App']['HideWindowToTray']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function IsSecureDNSEnabled() {
  return window['go']['main']['App']['IsSecureDNSEnabled']();
}

export function KillConflicts() {
  return window['go']['main']['App']['KillConflicts']();
}

export function KillWinws2() {
  return window['go']['main']['App']['KillWinws2']();
}

export function LoadCustomScript() {
  return window['go']['main']['App']['LoadCustomScript']();
}

export function LoadPingHistory() {
  return window['go']['main']['App']['LoadPingHistory']();
}

export function OpenCurrentLogFile() {
  return window['go']['main']['App']['OpenCurrentLogFile']();
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadBypassList(arg1) {
  return window['go']['main']['App']['ReadBypassList'](arg1);
}

export function RollbackEngineUpdate() {
  return window['go']['main']['App']['RollbackEngineUpdate']();
}

export function RunBypassComparison() {
  return window['go']['main']['App']['RunBypassComparison']();
}

export function RunDiagnostics() {
  return window['go']['main']['App']['RunDiagnostics']();
}

export function RunDoctor(arg1) {
  return window['go']['main']['App']['RunDoctor'](arg1);
}

export function SaveBypassList(arg1, arg2) {
  return window['go']['main']['App']['SaveBypassList'](arg1, arg2);
}

export function SaveCustomScript(arg1) {
  return window['go']['main']['App']['SaveCustomScript'](arg1);
}

export function SavePingHistory(arg1, arg2) {
  return window['go']['main']['App']['SavePingHistory'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetSecureDNS(arg1) {
  return window['go']['main']['App']['SetSecureDNS'](arg1);
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function ShowWindowFromTray() {
  return window['go']['main']['App']['ShowWindowFromTray']();
}

export function StartDoctor(arg1) {
  return window['go']['main']['App']['StartDoctor'](arg1);
}

export function StartEngine(arg1, arg2) {
  return window['go']['main']['App']['StartEngine'](arg1, arg2);
}

export function StopAutoReconnect() {
  return window['go']['main']['App']['StopAutoReconnect']();
}

export function StopEngine() {
  return window['go']['main']['App']['StopEngine']();
}

export function ToggleFavoriteProfile(arg1) {
  return window['go']['main']['App']['ToggleFavoriteProfile'](arg1);
}

export function TriggerTrayUpdate() {
  return window['go']['main']['App']['TriggerTrayUpdate']();
}

export function UpdateHostlistsNow() {
  return window['go']['main']['App']['UpdateHostlistsNow']();
}

export function VerifyEngineAssets() {
  return window['go']['main']['App']['VerifyEngineAssets']();
}
