// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSelectProfile(arg1) {
  return window['go']['main']['App']['AutoSelectProfile'](arg1);
}

export function AutoTune() {
  return window['go']['main']['App']['AutoTune']();
}

export function GetCurrentPing() {
  return window['go']['main']['App']['GetCurrentPing']();
}

export function GetEngineNames() {
  return window['go']['main']['App']['GetEngineNames']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProfiles(arg1) {
  return window['go']['main']['App']['GetProfiles'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function LoadCustomScript() {
  return window['go']['main']['App']['LoadCustomScript']();
}

export function SaveCustomScript(arg1) {
  return window['go']['main']['App']['SaveCustomScript'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function StartEngine(arg1, arg2) {
  return window['go']['main']['App']['StartEngine'](arg1, arg2);
}

export function StopEngine() {
  return window['go']['main']['App']['StopEngine']();
}

export function TestProfile(arg1, arg2) {
  return window['go']['main']['App']['TestProfile'](arg1, arg2);
}
