/**
 * Round-trips the visual strategy builder's settings through the generated Lua
 * script. The generator writes a `-- Params:` header that the parser reads back,
 * so reopening the editor restores the sliders instead of resetting them.
 */
export const generateLuaCode = (config: {
  fakeBlob: string;
  pos: string;
  fool: string;
  ttl: number;
}) => {
  return `-- AUTO-GENERATED BY UNBOUND LUA STRATEGY BUILDER
-- Version: 0.1.0-refresh
-- Params: fakeBlob=${config.fakeBlob}, pos=${config.pos}, fool=${config.fool}, ttl=${config.ttl}

-- Этот скрипт автоматически переопределяет стандартные функции zapret-antidpi.lua
-- на основе выбранных вами визуальных настроек.

local original_multisplit = multisplit
if original_multisplit then
  function multisplit(ctx, desync)
    desync.arg.pos = "${config.pos}"
    if "${config.fool}" ~= "none" then
      desync.arg.fool = "${config.fool}"
    end
    if ${config.ttl} > 0 then
      desync.arg.ip_ttl = ${config.ttl}
      desync.arg.ip6_ttl = ${config.ttl}
    end
    return original_multisplit(ctx, desync)
  end
end

local original_fake = fake
if original_fake then
  function fake(ctx, desync)
    desync.arg.blob = "${config.fakeBlob}"
    if ${config.ttl} > 0 then
      desync.arg.ip_ttl = ${config.ttl}
      desync.arg.ip6_ttl = ${config.ttl}
    end
    return original_fake(ctx, desync)
  end
end
`;
};

export const parseLuaCode = (code: string) => {
  const match = code.match(/-- Params: fakeBlob=([^,]+), pos=([^,]+), fool=([^,]+), ttl=(\d+)/);
  if (match) {
    return {
      isAuto: true,
      fakeBlob: match[1],
      pos: match[2],
      fool: match[3],
      ttl: parseInt(match[4], 10)
    };
  }
  return { isAuto: false, fakeBlob: 'fake_default_tls', pos: '1', fool: 'none', ttl: 0 };
};
